### PR TITLE
Owl Carousel

### PR DESCRIPTION
**Pull request by Mahak008**
Resolving issue #40 
Screenshot (331)

### CODE REVIEW

**Comment by Mahak008** [comment]
I am sorry, I closed this request by mistake. Kindly reconsider it once.

**Comment by vibgyor786** [comment]
@Mahak008 add your name in contributor section of readme .

**Comment by Mahak008** [comment]
> @Mahak008 add your name in contributor section of readme .

Done

**Comment by vibgyor786** [comment]
@Mahak008 please check once if you have pushed updated readme

**Comment by Mahak008** [comment]
> @Mahak008 please check once if you have pushed updated readme

It's done now

**Pull request merged**
