### PR TITLE
Added two components

### PR DESCRIPTION
**Pull request by Shreyaanp**
1. info card
2. github stat card

### CODE REVIEW

**Comment by Shreyaanp** [comment]
This is the output for the Github info card :
image
image

**Comment by Shreyaanp** [comment]
Info Card output :
Before on hover effect :
image
after on hover effect :
image

**Comment by vibgyor786** [comment]
add your name in contributor section of readme

**Comment by Shreyaanp** [comment]
Shreyaan Pradhan

**Pull request merged**
